'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const context = vm.createContext({ console });
vm.runInContext(fs.readFileSync(path.join(__dirname, '../js/constants.js'), 'utf8'), context);
const run = code => vm.runInContext(code, context);
assert.equal(run('Object.keys(getDefaultMastery()).length'), 27);
run('setMasteryOverrides({mc_atk_passive: 0, mc_hp_passive: 0.35})');
assert.equal(run('getDefaultMastery().mc_atk_passive'), 0);
assert.equal(run('getDefaultMastery().mc_hp_passive'), 0.35);
assert.equal(run('getDefaultMastery().mc_ta_passive'), 0.03);
run("currentUserId = 'user2'");
assert.equal(run('getDefaultMastery().mc_atk_passive'), 0.24);
run('setMasteryOverrides({mc_atk_passive: 0.12})');
run("currentUserId = 'user1'");
assert.equal(run('getDefaultMastery().mc_atk_passive'), 0);
run('var saved = JSON.parse(JSON.stringify({mc: {mastery: getDefaultMastery()}})); setMasteryOverrides(); setMasteryOverrides(saved.mc.mastery)');
assert.equal(run('getDefaultMastery().mc_atk_passive'), 0);
assert.equal(run('getDefaultMastery().mc_hp_passive'), 0.35);
run('setMasteryOverrides(undefined)');
assert.equal(run('getDefaultMastery().mc_atk_passive'), 0.22);
run('setMasteryOverrides({mc_atk_passive: NaN, mc_hp_passive: -1, mc_ta_passive: "0.5", mc_da_passive: Infinity, unknown: 1})');
assert.equal(run('getDefaultMastery().mc_hp_passive'), 0.20);
assert.equal(run('getDefaultMastery().mc_ta_passive'), 0.03);
assert.equal(run('getDefaultMastery().unknown'), undefined);
assert.equal(run('DEFAULT_MASTERY1.mc_atk_passive'), 0.22);
console.log('ok - 精通支持零值、用户隔离、JSON往返、旧配置回退与非法输入过滤');
